In [1]:
import numpy as np 

In [2]:
np.__version__

'1.19.1'

In [4]:
a = np.array([[1,2,3],[4,5,6]])
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = np.array([[1,2],[3,4],[5,6]])
b 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
a@b 

array([[22, 28],
       [49, 64]])

In [7]:
b@a 

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [8]:
np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [9]:
np.dot(b,a)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [11]:
np.multiply(a,a)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
np.multiply(b,b)

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.sum(a)

21

In [20]:
np.cumsum(a, axis= 0)

array([[1, 2, 3],
       [5, 7, 9]])

In [21]:
np.cumsum(a, axis= 1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [22]:
np.divide(a,3)

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [23]:
np.floor_divide(a, 3)

array([[0, 0, 1],
       [1, 1, 2]])

In [24]:
np.random.uniform(0,1,(3,3))

array([[0.70450655, 0.76536227, 0.28846305],
       [0.58875458, 0.05534495, 0.85757214],
       [0.74479889, 0.65255293, 0.999583  ]])

In [28]:
np.random.normal(0,1,(3,3))

array([[ 1.14798973, -0.68578066, -0.76832222],
       [ 2.37837186, -0.16904792,  1.41412465],
       [ 0.01137578, -0.73715112,  0.67966305]])

In [29]:
np.random.standard_normal((3,3))

array([[ 0.85900009,  0.95017548,  0.4443892 ],
       [ 0.37584657, -0.86238164,  1.21646427],
       [-1.97359574, -1.84210467, -0.22006893]])

In [30]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [32]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [33]:
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
my_mask = np.logical_and(a>2, a<5)

In [37]:
a[my_mask]

array([3, 4])

In [38]:
a 

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6])

In [43]:
np.intersect1d(a,b)

array([1, 2, 3, 4, 5, 6])

In [44]:
np.mean(a)

3.5

In [45]:
np.median(a)

3.5

In [46]:
np.std(a)

1.707825127659933

In [47]:
np.var(a)

2.9166666666666665

In [48]:
np.math.sqrt(np.var(a))

1.707825127659933